### ISSUE TITLE
[2024.09.04] carla_interface fails to build

### ISSUE THREAD

**Issue by esteve** [autowarefoundation/autoware-deb-packages#97]
`carla_interface` fails to build because of missing `ROS_VERSION` environment variable:

```console
2024-09-12T15:55:50.9852039Z dpkg-buildpackage: info: source package ros-humble-autoware-carla-interface
2024-09-12T15:55:50.9853198Z dpkg-buildpackage: info: source version 0-2024.09.12.15.51
2024-09-12T15:55:50.9853942Z dpkg-buildpackage: info: source distribution jammy
2024-09-12T15:55:50.9857176Z dpkg-buildpackage: info: source changed by Muhammad Raditya GIOVANNI <mradityagio@gmail.com>
2024-09-12T15:55:51.0087302Z  dpkg-source --before-build .
2024-09-12T15:55:51.0088025Z dpkg-buildpackage: info: host architecture amd64
2024-09-12T15:55:51.1109854Z dpkg-source: info: using options from package/debian/source/options: --auto-commit
2024-09-12T15:55:51.1856266Z  fakeroot debian/rules clean
2024-09-12T15:55:51.1964879Z dh clean -v --buildsystem=pybuild --with python3
2024-09-12T15:55:51.2794993Z    dh_auto_clean -O-v -O--buildsystem=pybuild
2024-09-12T15:55:51.4883644Z    pybuild --clean -i python{version} -p 3.10
2024-09-12T15:55:51.6055368Z I: pybuild base:239: python3.10 setup.py clean
2024-09-12T15:55:51.8921917Z Traceback (most recent call last):
2024-09-12T15:55:51.8979965Z   File "/<<BUILDDIR>>package/setup.py", line 6, in <module>
2024-09-12T15:55:51.8982891Z     ROS_VERSION = int(os.environ["ROS_VERSION"])
2024-09-12T15:55:51.8984681Z   File "/usr/lib/python3.10/os.py", line 680, in __getitem__
2024-09-12T15:55:51.8998100Z     raise KeyError(key) from None
2024-09-12T15:55:51.9004001Z KeyError: 'ROS_VERSION'
2024-09-12T15:55:51.9239228Z E: pybuild pybuild:369: clean: plugin distutils failed with: exit code=1: python3.10 setup.py clean
2024-09-12T15:55:51.9340382Z dh_auto_clean: error: pybuild --clean -i python{version} -p 3.10 returned exit code 13
2024-09-12T15:55:51.9388058Z make: *** [debian/rules:27: clean] Error 25
2024-09-12T15:55:51.9433959Z dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
2024-09-12T15:55:51.9489239Z --------------------------------------------------------------------------------
2024-09-12T15:55:51.9490453Z Build finished at 2024-09-12T15:55:51Z
```

**Comment by esteve** [comment]
Fix submitted https://github.com/autowarefoundation/autoware.universe/pull/8896

**Comment by esteve** [comment]
Closed via https://github.com/autowarefoundation/autoware.universe/pull/8896
